//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -O3
// source: tests/src/const_pool_neon.c

package tests

//go:noescape
func add_const_f32x4(v [16]byte) (result [16]byte)

//go:noescape
func mul_index_f32x4(v [16]byte) (result [16]byte)

//go:noescape
func weighted_sum_f32x4(v [16]byte) (result float32)
