//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -mavx2 -O3
// source: tests/src/const_pool_avx.c

package tests

//go:noescape
func add_const_ps256(v [32]byte) (result [32]byte)

//go:noescape
func mul_index_ps256(v [32]byte) (result [32]byte)

//go:noescape
func hsum_ps256(v [32]byte) (result float32)
