//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -mavx2 -O3
// source: tests/src/const_pool_avx.c

#include "textflag.h"

// Constant pool data
DATA CPI0_0<>+0(SB)/4, $0x41200000
DATA CPI0_0<>+4(SB)/4, $0x41a00000
DATA CPI0_0<>+8(SB)/4, $0x41f00000
DATA CPI0_0<>+12(SB)/4, $0x42200000
DATA CPI0_0<>+16(SB)/4, $0x42480000
DATA CPI0_0<>+20(SB)/4, $0x42700000
DATA CPI0_0<>+24(SB)/4, $0x428c0000
DATA CPI0_0<>+28(SB)/4, $0x42a00000
GLOBL CPI0_0<>(SB), (RODATA|NOPTR), $32
DATA CPI1_0<>+0(SB)/4, $0x3f800000
DATA CPI1_0<>+4(SB)/4, $0x40000000
DATA CPI1_0<>+8(SB)/4, $0x40400000
DATA CPI1_0<>+12(SB)/4, $0x40800000
DATA CPI1_0<>+16(SB)/4, $0x40a00000
DATA CPI1_0<>+20(SB)/4, $0x40c00000
DATA CPI1_0<>+24(SB)/4, $0x40e00000
DATA CPI1_0<>+28(SB)/4, $0x41000000
GLOBL CPI1_0<>(SB), (RODATA|NOPTR), $32

TEXT ·add_const_ps256(SB), $0-64
	MOVQ         v_0+0(FP), AX
	MOVQ         v_8+8(FP), BX
	MOVQ         AX, X14
	PINSRQ       $1, BX, X14
	MOVQ         v_16+16(FP), AX
	MOVQ         v_24+24(FP), BX
	MOVQ         AX, X15
	PINSRQ       $1, BX, X15
	VINSERTF128  $1, X15, Y14, Y0
	VADDPS       CPI0_0<>(SB), Y0     // vaddps	LCPI0_0(%rip), %ymm0, %ymm0
	VEXTRACTF128 $0, Y0, X14
	MOVQ         X14, AX
	PEXTRQ       $1, X14, BX
	MOVQ         AX, result_0+32(FP)
	MOVQ         BX, result_8+40(FP)
	VEXTRACTF128 $1, Y0, X14
	MOVQ         X14, AX
	PEXTRQ       $1, X14, BX
	MOVQ         AX, result_16+48(FP)
	MOVQ         BX, result_24+56(FP)
	RET

TEXT ·mul_index_ps256(SB), $0-64
	MOVQ         v_0+0(FP), AX
	MOVQ         v_8+8(FP), BX
	MOVQ         AX, X14
	PINSRQ       $1, BX, X14
	MOVQ         v_16+16(FP), AX
	MOVQ         v_24+24(FP), BX
	MOVQ         AX, X15
	PINSRQ       $1, BX, X15
	VINSERTF128  $1, X15, Y14, Y0
	VMULPS       CPI1_0<>(SB), Y0     // vmulps	LCPI1_0(%rip), %ymm0, %ymm0
	VEXTRACTF128 $0, Y0, X14
	MOVQ         X14, AX
	PEXTRQ       $1, X14, BX
	MOVQ         AX, result_0+32(FP)
	MOVQ         BX, result_8+40(FP)
	VEXTRACTF128 $1, Y0, X14
	MOVQ         X14, AX
	PEXTRQ       $1, X14, BX
	MOVQ         AX, result_16+48(FP)
	MOVQ         BX, result_24+56(FP)
	RET

TEXT ·hsum_ps256(SB), $0-36
	MOVQ        v_0+0(FP), AX
	MOVQ        v_8+8(FP), BX
	MOVQ        AX, X14
	PINSRQ      $1, BX, X14
	MOVQ        v_16+16(FP), AX
	MOVQ        v_24+24(FP), BX
	MOVQ        AX, X15
	PINSRQ      $1, BX, X15
	VINSERTF128 $1, X15, Y14, Y0
	LONG        $0x197de3c4; WORD $0x01c1 // vextractf128	$1, %ymm0, %xmm1
	LONG        $0xc058f0c5               // vaddps	%xmm0, %xmm1, %xmm0
	LONG        $0xc07cfbc5               // vhaddps	%xmm0, %xmm0, %xmm0
	LONG        $0xc07cfbc5               // vhaddps	%xmm0, %xmm0, %xmm0
	WORD        $0xf8c5; BYTE $0x77       // vzeroupper
	MOVSS       X0, result+32(FP)
	RET
