//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -O3
// source: tests/src/const_pool_neon.c

#include "textflag.h"

// Constant pool data
DATA CPI0_0<>+0(SB)/4, $0x41200000
DATA CPI0_0<>+4(SB)/4, $0x41a00000
DATA CPI0_0<>+8(SB)/4, $0x41f00000
DATA CPI0_0<>+12(SB)/4, $0x42200000
GLOBL CPI0_0<>(SB), (RODATA|NOPTR), $16
DATA CPI1_0<>+0(SB)/4, $0x3f800000
DATA CPI1_0<>+4(SB)/4, $0x40000000
DATA CPI1_0<>+8(SB)/4, $0x40400000
DATA CPI1_0<>+12(SB)/4, $0x40800000
GLOBL CPI1_0<>(SB), (RODATA|NOPTR), $16

TEXT ·add_const_f32x4(SB), $0-32
	MOVD v_0+0(FP), R9
	MOVD v_8+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD $CPI0_0<>(SB), R8
	VLD1 (R8), [V1.B16]
	WORD $0x4e21d400          // fadd.4s	v0, v0, v1
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result_0+16(FP)
	MOVD R10, result_8+24(FP)
	RET

TEXT ·mul_index_f32x4(SB), $0-32
	MOVD v_0+0(FP), R9
	MOVD v_8+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD $CPI1_0<>(SB), R8
	VLD1 (R8), [V1.B16]
	WORD $0x6e21dc00          // fmul.4s	v0, v0, v1
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result_0+16(FP)
	MOVD R10, result_8+24(FP)
	RET

TEXT ·weighted_sum_f32x4(SB), $0-20
	MOVD  v_0+0(FP), R9
	MOVD  v_8+8(FP), R10
	VMOV  R9, V0.D[0]
	VMOV  R10, V0.D[1]
	WORD  $0x4f02f601       // fmov.4s	v1, #0.25000000
	WORD  $0x6e21dc00       // fmul.4s	v0, v0, v1
	WORD  $0x6e20d400       // faddp.4s	v0, v0, v0
	WORD  $0x7e30d800       // faddp.2s	s0, v0
	FMOVS F0, result+16(FP)
	RET
