//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -O0
// source: src/neon.c

package tests

//go:noescape
func add_f32x4(a, b [16]byte) (result [16]byte)

//go:noescape
func mul_f32x4(a, b [16]byte) (result [16]byte)

//go:noescape
func fma_f32x4(a, b, c [16]byte) (result [16]byte)

//go:noescape
func add_i32x4(a, b [16]byte) (result [16]byte)

//go:noescape
func hsum_f32x4(v [16]byte) (result float32)

//go:noescape
func dot_f32x4(a, b [16]byte) (result float32)

//go:noescape
func add_f32x2(a, b [8]byte) (result [8]byte)

//go:noescape
func mul_f32x2(a, b [8]byte) (result [8]byte)

//go:noescape
func add_i32x2(a, b [8]byte) (result [8]byte)

//go:noescape
func hsum_f32x2(v [8]byte) (result float32)

//go:noescape
func add_f32x4x2(a, b [32]byte) (result [32]byte)

//go:noescape
func make_f32x4x2(a, b [16]byte) (result [32]byte)

//go:noescape
func sum_f32x4x2(v [32]byte) (result float32)
