//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -O0
// source: src/neon.c

TEXT ·add_f32x4(SB), $0-48
	MOVD a_0+0(FP), R9
	MOVD a_8+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD b_0+16(FP), R9
	MOVD b_8+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	WORD $0xd10143ff          // sub	sp, sp, #80
	WORD $0x3d8007e0          // str	q0, [sp, #16]
	WORD $0x3d8003e1          // str	q1, [sp]
	WORD $0x3dc007e1          // ldr	q1, [sp, #16]
	WORD $0x3dc003e0          // ldr	q0, [sp]
	WORD $0x3d8013e1          // str	q1, [sp, #64]
	WORD $0x3d800fe0          // str	q0, [sp, #48]
	WORD $0x3dc013e0          // ldr	q0, [sp, #64]
	WORD $0x3dc00fe1          // ldr	q1, [sp, #48]
	WORD $0x4e21d400          // fadd	v0.4s, v0.4s, v1.4s
	WORD $0x3d800be0          // str	q0, [sp, #32]
	WORD $0x3dc00be0          // ldr	q0, [sp, #32]
	WORD $0x910143ff          // add	sp, sp, #80
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result_0+32(FP)
	MOVD R10, result_8+40(FP)
	RET

TEXT ·mul_f32x4(SB), $0-48
	MOVD a_0+0(FP), R9
	MOVD a_8+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD b_0+16(FP), R9
	MOVD b_8+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	WORD $0xd10143ff          // sub	sp, sp, #80
	WORD $0x3d8007e0          // str	q0, [sp, #16]
	WORD $0x3d8003e1          // str	q1, [sp]
	WORD $0x3dc007e1          // ldr	q1, [sp, #16]
	WORD $0x3dc003e0          // ldr	q0, [sp]
	WORD $0x3d8013e1          // str	q1, [sp, #64]
	WORD $0x3d800fe0          // str	q0, [sp, #48]
	WORD $0x3dc013e0          // ldr	q0, [sp, #64]
	WORD $0x3dc00fe1          // ldr	q1, [sp, #48]
	WORD $0x6e21dc00          // fmul	v0.4s, v0.4s, v1.4s
	WORD $0x3d800be0          // str	q0, [sp, #32]
	WORD $0x3dc00be0          // ldr	q0, [sp, #32]
	WORD $0x910143ff          // add	sp, sp, #80
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result_0+32(FP)
	MOVD R10, result_8+40(FP)
	RET

TEXT ·fma_f32x4(SB), $0-64
	MOVD a_0+0(FP), R9
	MOVD a_8+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD b_0+16(FP), R9
	MOVD b_8+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	MOVD c_0+32(FP), R9
	MOVD c_8+40(FP), R10
	VMOV R9, V2.D[0]
	VMOV R10, V2.D[1]
	WORD $0xd10203ff          // sub	sp, sp, #128
	WORD $0x3d800be0          // str	q0, [sp, #32]
	WORD $0x3d8007e1          // str	q1, [sp, #16]
	WORD $0x3d8003e2          // str	q2, [sp]
	WORD $0x3dc003e2          // ldr	q2, [sp]
	WORD $0x3dc00be1          // ldr	q1, [sp, #32]
	WORD $0x3dc007e0          // ldr	q0, [sp, #16]
	WORD $0x3d801fe2          // str	q2, [sp, #112]
	WORD $0x3d801be1          // str	q1, [sp, #96]
	WORD $0x3d8017e0          // str	q0, [sp, #80]
	WORD $0x3dc01fe0          // ldr	q0, [sp, #112]
	WORD $0x3dc01be2          // ldr	q2, [sp, #96]
	WORD $0x3dc017e1          // ldr	q1, [sp, #80]
	WORD $0x4e22cc20          // fmla	v0.4s, v1.4s, v2.4s
	WORD $0x3d800fe0          // str	q0, [sp, #48]
	WORD $0x3dc00fe0          // ldr	q0, [sp, #48]
	WORD $0x3d8013e0          // str	q0, [sp, #64]
	WORD $0x3dc013e0          // ldr	q0, [sp, #64]
	WORD $0x910203ff          // add	sp, sp, #128
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result_0+48(FP)
	MOVD R10, result_8+56(FP)
	RET

TEXT ·add_i32x4(SB), $0-48
	MOVD a_0+0(FP), R9
	MOVD a_8+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD b_0+16(FP), R9
	MOVD b_8+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	WORD $0xd10143ff          // sub	sp, sp, #80
	WORD $0x3d8007e0          // str	q0, [sp, #16]
	WORD $0x3d8003e1          // str	q1, [sp]
	WORD $0x3dc007e1          // ldr	q1, [sp, #16]
	WORD $0x3dc003e0          // ldr	q0, [sp]
	WORD $0x3d8013e1          // str	q1, [sp, #64]
	WORD $0x3d800fe0          // str	q0, [sp, #48]
	WORD $0x3dc013e0          // ldr	q0, [sp, #64]
	WORD $0x3dc00fe1          // ldr	q1, [sp, #48]
	WORD $0x4ea18400          // add	v0.4s, v0.4s, v1.4s
	WORD $0x3d800be0          // str	q0, [sp, #32]
	WORD $0x3dc00be0          // ldr	q0, [sp, #32]
	WORD $0x910143ff          // add	sp, sp, #80
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result_0+32(FP)
	MOVD R10, result_8+40(FP)
	RET

TEXT ·hsum_f32x4(SB), $0-20
	MOVD  v_0+0(FP), R9
	MOVD  v_8+8(FP), R10
	VMOV  R9, V0.D[0]
	VMOV  R10, V0.D[1]
	WORD  $0xd100c3ff       // sub	sp, sp, #48
	WORD  $0x3d8003e0       // str	q0, [sp]
	WORD  $0x3dc003e0       // ldr	q0, [sp]
	WORD  $0x3d800be0       // str	q0, [sp, #32]
	WORD  $0x3dc00be0       // ldr	q0, [sp, #32]
	WORD  $0x6e20d400       // faddp	v0.4s, v0.4s, v0.4s
	WORD  $0x7e30d800       // faddp	s0, v0.2s
	WORD  $0xbd001be0       // str	s0, [sp, #24]
	WORD  $0xbd401be0       // ldr	s0, [sp, #24]
	WORD  $0xbd001fe0       // str	s0, [sp, #28]
	WORD  $0xbd401fe0       // ldr	s0, [sp, #28]
	WORD  $0x9100c3ff       // add	sp, sp, #48
	FMOVS F0, result+16(FP)
	RET

TEXT ·dot_f32x4(SB), $0-36
	MOVD  a_0+0(FP), R9
	MOVD  a_8+8(FP), R10
	VMOV  R9, V0.D[0]
	VMOV  R10, V0.D[1]
	MOVD  b_0+16(FP), R9
	MOVD  b_8+24(FP), R10
	VMOV  R9, V1.D[0]
	VMOV  R10, V1.D[1]
	WORD  $0xd10203ff       // sub	sp, sp, #128
	WORD  $0x3d800be0       // str	q0, [sp, #32]
	WORD  $0x3d8007e1       // str	q1, [sp, #16]
	WORD  $0x3dc00be1       // ldr	q1, [sp, #32]
	WORD  $0x3dc007e0       // ldr	q0, [sp, #16]
	WORD  $0x3d8017e1       // str	q1, [sp, #80]
	WORD  $0x3d8013e0       // str	q0, [sp, #64]
	WORD  $0x3dc017e0       // ldr	q0, [sp, #80]
	WORD  $0x3dc013e1       // ldr	q1, [sp, #64]
	WORD  $0x6e21dc00       // fmul	v0.4s, v0.4s, v1.4s
	WORD  $0x3d800fe0       // str	q0, [sp, #48]
	WORD  $0x3dc00fe0       // ldr	q0, [sp, #48]
	WORD  $0x3d8003e0       // str	q0, [sp]
	WORD  $0x3dc003e0       // ldr	q0, [sp]
	WORD  $0x3d801fe0       // str	q0, [sp, #112]
	WORD  $0x3dc01fe0       // ldr	q0, [sp, #112]
	WORD  $0x6e20d400       // faddp	v0.4s, v0.4s, v0.4s
	WORD  $0x7e30d800       // faddp	s0, v0.2s
	WORD  $0xbd006be0       // str	s0, [sp, #104]
	WORD  $0xbd406be0       // ldr	s0, [sp, #104]
	WORD  $0xbd006fe0       // str	s0, [sp, #108]
	WORD  $0xbd406fe0       // ldr	s0, [sp, #108]
	WORD  $0x910203ff       // add	sp, sp, #128
	FMOVS F0, result+32(FP)
	RET

TEXT ·add_f32x2(SB), $0-24
	MOVD a+0(FP), R9
	VMOV R9, V0.D[0]
	MOVD b+8(FP), R9
	VMOV R9, V1.D[0]
	WORD $0xd100c3ff       // sub	sp, sp, #48
	WORD $0xfd000be0       // str	d0, [sp, #16]
	WORD $0xfd0007e1       // str	d1, [sp, #8]
	WORD $0xfd400be1       // ldr	d1, [sp, #16]
	WORD $0xfd4007e0       // ldr	d0, [sp, #8]
	WORD $0xfd0017e1       // str	d1, [sp, #40]
	WORD $0xfd0013e0       // str	d0, [sp, #32]
	WORD $0xfd4017e0       // ldr	d0, [sp, #40]
	WORD $0xfd4013e1       // ldr	d1, [sp, #32]
	WORD $0x0e21d400       // fadd	v0.2s, v0.2s, v1.2s
	WORD $0xfd000fe0       // str	d0, [sp, #24]
	WORD $0xfd400fe0       // ldr	d0, [sp, #24]
	WORD $0x9100c3ff       // add	sp, sp, #48
	VMOV V0.D[0], R9
	MOVD R9, result+16(FP)
	RET

TEXT ·mul_f32x2(SB), $0-24
	MOVD a+0(FP), R9
	VMOV R9, V0.D[0]
	MOVD b+8(FP), R9
	VMOV R9, V1.D[0]
	WORD $0xd100c3ff       // sub	sp, sp, #48
	WORD $0xfd000be0       // str	d0, [sp, #16]
	WORD $0xfd0007e1       // str	d1, [sp, #8]
	WORD $0xfd400be1       // ldr	d1, [sp, #16]
	WORD $0xfd4007e0       // ldr	d0, [sp, #8]
	WORD $0xfd0017e1       // str	d1, [sp, #40]
	WORD $0xfd0013e0       // str	d0, [sp, #32]
	WORD $0xfd4017e0       // ldr	d0, [sp, #40]
	WORD $0xfd4013e1       // ldr	d1, [sp, #32]
	WORD $0x2e21dc00       // fmul	v0.2s, v0.2s, v1.2s
	WORD $0xfd000fe0       // str	d0, [sp, #24]
	WORD $0xfd400fe0       // ldr	d0, [sp, #24]
	WORD $0x9100c3ff       // add	sp, sp, #48
	VMOV V0.D[0], R9
	MOVD R9, result+16(FP)
	RET

TEXT ·add_i32x2(SB), $0-24
	MOVD a+0(FP), R9
	VMOV R9, V0.D[0]
	MOVD b+8(FP), R9
	VMOV R9, V1.D[0]
	WORD $0xd100c3ff       // sub	sp, sp, #48
	WORD $0xfd000be0       // str	d0, [sp, #16]
	WORD $0xfd0007e1       // str	d1, [sp, #8]
	WORD $0xfd400be1       // ldr	d1, [sp, #16]
	WORD $0xfd4007e0       // ldr	d0, [sp, #8]
	WORD $0xfd0017e1       // str	d1, [sp, #40]
	WORD $0xfd0013e0       // str	d0, [sp, #32]
	WORD $0xfd4017e0       // ldr	d0, [sp, #40]
	WORD $0xfd4013e1       // ldr	d1, [sp, #32]
	WORD $0x0ea18400       // add	v0.2s, v0.2s, v1.2s
	WORD $0xfd000fe0       // str	d0, [sp, #24]
	WORD $0xfd400fe0       // ldr	d0, [sp, #24]
	WORD $0x9100c3ff       // add	sp, sp, #48
	VMOV V0.D[0], R9
	MOVD R9, result+16(FP)
	RET

TEXT ·hsum_f32x2(SB), $0-12
	MOVD  v+0(FP), R9
	VMOV  R9, V0.D[0]
	WORD  $0xd10083ff      // sub	sp, sp, #32
	WORD  $0xfd0007e0      // str	d0, [sp, #8]
	WORD  $0xfd4007e0      // ldr	d0, [sp, #8]
	WORD  $0xfd000fe0      // str	d0, [sp, #24]
	WORD  $0xfd400fe0      // ldr	d0, [sp, #24]
	WORD  $0x7e30d800      // faddp	s0, v0.2s
	WORD  $0xbd0013e0      // str	s0, [sp, #16]
	WORD  $0xbd4013e0      // ldr	s0, [sp, #16]
	WORD  $0xbd0017e0      // str	s0, [sp, #20]
	WORD  $0xbd4017e0      // ldr	s0, [sp, #20]
	WORD  $0x910083ff      // add	sp, sp, #32
	FMOVS F0, result+8(FP)
	RET

TEXT ·add_f32x4x2(SB), $0-96
	MOVD a_0+0(FP), R9
	MOVD a_8+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD a_16+16(FP), R9
	MOVD a_24+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	MOVD b_0+32(FP), R9
	MOVD b_8+40(FP), R10
	VMOV R9, V2.D[0]
	VMOV R10, V2.D[1]
	MOVD b_16+48(FP), R9
	MOVD b_24+56(FP), R10
	VMOV R9, V3.D[0]
	VMOV R10, V3.D[1]
	WORD $0xd10303ff           // sub	sp, sp, #192
	WORD $0x3d800be0           // str	q0, [sp, #32]
	WORD $0x3d800fe1           // str	q1, [sp, #48]
	WORD $0x3d8003e2           // str	q2, [sp]
	WORD $0x3d8007e3           // str	q3, [sp, #16]
	WORD $0x3dc00be1           // ldr	q1, [sp, #32]
	WORD $0x3dc003e0           // ldr	q0, [sp]
	WORD $0x3d802fe1           // str	q1, [sp, #176]
	WORD $0x3d802be0           // str	q0, [sp, #160]
	WORD $0x3dc02fe0           // ldr	q0, [sp, #176]
	WORD $0x3dc02be1           // ldr	q1, [sp, #160]
	WORD $0x4e21d400           // fadd	v0.4s, v0.4s, v1.4s
	WORD $0x3d8027e0           // str	q0, [sp, #144]
	WORD $0x3dc027e0           // ldr	q0, [sp, #144]
	WORD $0x3d8013e0           // str	q0, [sp, #64]
	WORD $0x3dc00fe1           // ldr	q1, [sp, #48]
	WORD $0x3dc007e0           // ldr	q0, [sp, #16]
	WORD $0x3d8023e1           // str	q1, [sp, #128]
	WORD $0x3d801fe0           // str	q0, [sp, #112]
	WORD $0x3dc023e0           // ldr	q0, [sp, #128]
	WORD $0x3dc01fe1           // ldr	q1, [sp, #112]
	WORD $0x4e21d400           // fadd	v0.4s, v0.4s, v1.4s
	WORD $0x3d801be0           // str	q0, [sp, #96]
	WORD $0x3dc01be0           // ldr	q0, [sp, #96]
	WORD $0x3d8017e0           // str	q0, [sp, #80]
	WORD $0x3dc013e0           // ldr	q0, [sp, #64]
	WORD $0x3dc017e1           // ldr	q1, [sp, #80]
	WORD $0x910303ff           // add	sp, sp, #192
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result_0+64(FP)
	MOVD R10, result_8+72(FP)
	VMOV V1.D[0], R9
	VMOV V1.D[1], R10
	MOVD R9, result_16+80(FP)
	MOVD R10, result_24+88(FP)
	RET

TEXT ·make_f32x4x2(SB), $0-64
	MOVD a_0+0(FP), R9
	MOVD a_8+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD b_0+16(FP), R9
	MOVD b_8+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	WORD $0xd10103ff           // sub	sp, sp, #64
	WORD $0x3d8007e0           // str	q0, [sp, #16]
	WORD $0x3d8003e1           // str	q1, [sp]
	WORD $0x3dc007e0           // ldr	q0, [sp, #16]
	WORD $0x3d800be0           // str	q0, [sp, #32]
	WORD $0x3dc003e0           // ldr	q0, [sp]
	WORD $0x3d800fe0           // str	q0, [sp, #48]
	WORD $0x3dc00be0           // ldr	q0, [sp, #32]
	WORD $0x3dc00fe1           // ldr	q1, [sp, #48]
	WORD $0x910103ff           // add	sp, sp, #64
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result_0+32(FP)
	MOVD R10, result_8+40(FP)
	VMOV V1.D[0], R9
	VMOV V1.D[1], R10
	MOVD R9, result_16+48(FP)
	MOVD R10, result_24+56(FP)
	RET

TEXT ·sum_f32x4x2(SB), $0-36
	MOVD  v_0+0(FP), R9
	MOVD  v_8+8(FP), R10
	VMOV  R9, V0.D[0]
	VMOV  R10, V0.D[1]
	MOVD  v_16+16(FP), R9
	MOVD  v_24+24(FP), R10
	VMOV  R9, V1.D[0]
	VMOV  R10, V1.D[1]
	WORD  $0xd101c3ff       // sub	sp, sp, #112
	WORD  $0x3d8007e0       // str	q0, [sp, #16]
	WORD  $0x3d800be1       // str	q1, [sp, #32]
	WORD  $0x3dc007e0       // ldr	q0, [sp, #16]
	WORD  $0x3d801be0       // str	q0, [sp, #96]
	WORD  $0x3dc01be0       // ldr	q0, [sp, #96]
	WORD  $0x6e20d400       // faddp	v0.4s, v0.4s, v0.4s
	WORD  $0x7e30d800       // faddp	s0, v0.2s
	WORD  $0xbd005be0       // str	s0, [sp, #88]
	WORD  $0xbd405be0       // ldr	s0, [sp, #88]
	WORD  $0xbd005fe0       // str	s0, [sp, #92]
	WORD  $0xbd405fe0       // ldr	s0, [sp, #92]
	WORD  $0xbd000fe0       // str	s0, [sp, #12]
	WORD  $0x3dc00be0       // ldr	q0, [sp, #32]
	WORD  $0x3d8013e0       // str	q0, [sp, #64]
	WORD  $0x3dc013e0       // ldr	q0, [sp, #64]
	WORD  $0x6e20d400       // faddp	v0.4s, v0.4s, v0.4s
	WORD  $0x7e30d800       // faddp	s0, v0.2s
	WORD  $0xbd003be0       // str	s0, [sp, #56]
	WORD  $0xbd403be0       // ldr	s0, [sp, #56]
	WORD  $0xbd003fe0       // str	s0, [sp, #60]
	WORD  $0xbd403fe0       // ldr	s0, [sp, #60]
	WORD  $0xbd000be0       // str	s0, [sp, #8]
	WORD  $0xbd400fe0       // ldr	s0, [sp, #12]
	WORD  $0xbd400be1       // ldr	s1, [sp, #8]
	WORD  $0x1e212800       // fadd	s0, s0, s1
	WORD  $0x9101c3ff       // add	sp, sp, #112
	FMOVS F0, result+32(FP)
	RET
