//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -O3
// source: tests/src/neon.c

TEXT ·add_f32x4(SB), $0-48
	MOVD a+0(FP), R9
	MOVD a+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD b+16(FP), R9
	MOVD b+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	WORD $0xa9bf7bfd        // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd        // mov	x29, sp
	WORD $0x4e21d400        // fadd	v0.4s, v0.4s, v1.4s
	WORD $0xa8c17bfd        // ldp	x29, x30, [sp], #16
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result+32(FP)
	MOVD R10, result+40(FP)
	RET

TEXT ·mul_f32x4(SB), $0-48
	MOVD a+0(FP), R9
	MOVD a+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD b+16(FP), R9
	MOVD b+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	WORD $0xa9bf7bfd        // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd        // mov	x29, sp
	WORD $0x6e21dc00        // fmul	v0.4s, v0.4s, v1.4s
	WORD $0xa8c17bfd        // ldp	x29, x30, [sp], #16
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result+32(FP)
	MOVD R10, result+40(FP)
	RET

TEXT ·fma_f32x4(SB), $0-64
	MOVD a+0(FP), R9
	MOVD a+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD b+16(FP), R9
	MOVD b+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	MOVD c+32(FP), R9
	MOVD c+40(FP), R10
	VMOV R9, V2.D[0]
	VMOV R10, V2.D[1]
	WORD $0xa9bf7bfd        // stp	x29, x30, [sp, #-16]!
	WORD $0x4e20cc22        // fmla	v2.4s, v1.4s, v0.4s
	WORD $0x910003fd        // mov	x29, sp
	WORD $0x4ea21c40        // mov	v0.16b, v2.16b
	WORD $0xa8c17bfd        // ldp	x29, x30, [sp], #16
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result+48(FP)
	MOVD R10, result+56(FP)
	RET

TEXT ·add_i32x4(SB), $0-48
	MOVD a+0(FP), R9
	MOVD a+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD b+16(FP), R9
	MOVD b+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	WORD $0xa9bf7bfd        // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd        // mov	x29, sp
	WORD $0x4ea08420        // add	v0.4s, v1.4s, v0.4s
	WORD $0xa8c17bfd        // ldp	x29, x30, [sp], #16
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result+32(FP)
	MOVD R10, result+40(FP)
	RET

TEXT ·hsum_f32x4(SB), $0-24
	MOVD  v+0(FP), R9
	MOVD  v+8(FP), R10
	VMOV  R9, V0.D[0]
	VMOV  R10, V0.D[1]
	WORD  $0xa9bf7bfd       // stp	x29, x30, [sp, #-16]!
	WORD  $0x6e20d400       // faddp	v0.4s, v0.4s, v0.4s
	WORD  $0x910003fd       // mov	x29, sp
	WORD  $0x7e30d800       // faddp	s0, v0.2s
	WORD  $0xa8c17bfd       // ldp	x29, x30, [sp], #16
	FMOVS F0, result+16(FP)
	RET

TEXT ·dot_f32x4(SB), $0-40
	MOVD  a+0(FP), R9
	MOVD  a+8(FP), R10
	VMOV  R9, V0.D[0]
	VMOV  R10, V0.D[1]
	MOVD  b+16(FP), R9
	MOVD  b+24(FP), R10
	VMOV  R9, V1.D[0]
	VMOV  R10, V1.D[1]
	WORD  $0xa9bf7bfd       // stp	x29, x30, [sp, #-16]!
	WORD  $0x6e21dc00       // fmul	v0.4s, v0.4s, v1.4s
	WORD  $0x910003fd       // mov	x29, sp
	WORD  $0x6e20d400       // faddp	v0.4s, v0.4s, v0.4s
	WORD  $0x7e30d800       // faddp	s0, v0.2s
	WORD  $0xa8c17bfd       // ldp	x29, x30, [sp], #16
	FMOVS F0, result+32(FP)
	RET

TEXT ·add_f32x2(SB), $0-24
	MOVD a+0(FP), R9
	VMOV R9, V0.D[0]
	MOVD b+8(FP), R9
	VMOV R9, V1.D[0]
	WORD $0xa9bf7bfd       // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd       // mov	x29, sp
	WORD $0x0e21d400       // fadd	v0.2s, v0.2s, v1.2s
	WORD $0xa8c17bfd       // ldp	x29, x30, [sp], #16
	VMOV V0.D[0], R9
	MOVD R9, result+16(FP)
	RET

TEXT ·mul_f32x2(SB), $0-24
	MOVD a+0(FP), R9
	VMOV R9, V0.D[0]
	MOVD b+8(FP), R9
	VMOV R9, V1.D[0]
	WORD $0xa9bf7bfd       // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd       // mov	x29, sp
	WORD $0x2e21dc00       // fmul	v0.2s, v0.2s, v1.2s
	WORD $0xa8c17bfd       // ldp	x29, x30, [sp], #16
	VMOV V0.D[0], R9
	MOVD R9, result+16(FP)
	RET

TEXT ·add_i32x2(SB), $0-24
	MOVD a+0(FP), R9
	VMOV R9, V0.D[0]
	MOVD b+8(FP), R9
	VMOV R9, V1.D[0]
	WORD $0xa9bf7bfd       // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd       // mov	x29, sp
	WORD $0x0ea08420       // add	v0.2s, v1.2s, v0.2s
	WORD $0xa8c17bfd       // ldp	x29, x30, [sp], #16
	VMOV V0.D[0], R9
	MOVD R9, result+16(FP)
	RET

TEXT ·hsum_f32x2(SB), $0-16
	MOVD  v+0(FP), R9
	VMOV  R9, V0.D[0]
	WORD  $0xa9bf7bfd      // stp	x29, x30, [sp, #-16]!
	WORD  $0x910003fd      // mov	x29, sp
	WORD  $0x7e30d800      // faddp	s0, v0.2s
	WORD  $0xa8c17bfd      // ldp	x29, x30, [sp], #16
	FMOVS F0, result+8(FP)
	RET

TEXT ·add_f32x4x2(SB), $0-96
	MOVD a+0(FP), R9
	MOVD a+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD a+16(FP), R9
	MOVD a+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	MOVD b+32(FP), R9
	MOVD b+40(FP), R10
	VMOV R9, V2.D[0]
	VMOV R10, V2.D[1]
	MOVD b+48(FP), R9
	MOVD b+56(FP), R10
	VMOV R9, V3.D[0]
	VMOV R10, V3.D[1]
	WORD $0xa9bf7bfd        // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd        // mov	x29, sp
	WORD $0x4e23d421        // fadd	v1.4s, v1.4s, v3.4s
	WORD $0x4e22d400        // fadd	v0.4s, v0.4s, v2.4s
	WORD $0xa8c17bfd        // ldp	x29, x30, [sp], #16
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result+64(FP)
	MOVD R10, result+72(FP)
	VMOV V1.D[0], R9
	VMOV V1.D[1], R10
	MOVD R9, result+80(FP)
	MOVD R10, result+88(FP)
	RET

TEXT ·make_f32x4x2(SB), $0-64
	MOVD a+0(FP), R9
	MOVD a+8(FP), R10
	VMOV R9, V0.D[0]
	VMOV R10, V0.D[1]
	MOVD b+16(FP), R9
	MOVD b+24(FP), R10
	VMOV R9, V1.D[0]
	VMOV R10, V1.D[1]
	WORD $0xa9bf7bfd        // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd        // mov	x29, sp
	WORD $0xa8c17bfd        // ldp	x29, x30, [sp], #16
	VMOV V0.D[0], R9
	VMOV V0.D[1], R10
	MOVD R9, result+32(FP)
	MOVD R10, result+40(FP)
	VMOV V1.D[0], R9
	VMOV V1.D[1], R10
	MOVD R9, result+48(FP)
	MOVD R10, result+56(FP)
	RET

TEXT ·sum_f32x4x2(SB), $0-40
	MOVD  v+0(FP), R9
	MOVD  v+8(FP), R10
	VMOV  R9, V0.D[0]
	VMOV  R10, V0.D[1]
	MOVD  v+16(FP), R9
	MOVD  v+24(FP), R10
	VMOV  R9, V1.D[0]
	VMOV  R10, V1.D[1]
	WORD  $0xa9bf7bfd       // stp	x29, x30, [sp, #-16]!
	WORD  $0x6e20d400       // faddp	v0.4s, v0.4s, v0.4s
	WORD  $0x6e21d421       // faddp	v1.4s, v1.4s, v1.4s
	WORD  $0x910003fd       // mov	x29, sp
	WORD  $0x7e30d800       // faddp	s0, v0.2s
	WORD  $0x7e30d821       // faddp	s1, v1.2s
	WORD  $0x1e212800       // fadd	s0, s0, s1
	WORD  $0xa8c17bfd       // ldp	x29, x30, [sp], #16
	FMOVS F0, result+32(FP)
	RET
