//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv9-a+sme -O3
// source: tests/src/sme_matmul.c

package tests

import "unsafe"

//go:noescape
func sme_fmopa_tile(a, b, c unsafe.Pointer)

//go:noescape
func sme_matmul_f32(at, b, c, pm, pn, pk unsafe.Pointer)

//go:noescape
func sme_dot16(a, b, c unsafe.Pointer)
