//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -mavx2 -mfma -O3
// source: tests/src/sse_avx.c

package tests

//go:noescape
func add_ps(a, b [16]byte) (result [16]byte)

//go:noescape
func mul_ps(a, b [16]byte) (result [16]byte)

//go:noescape
func fma_ps(a, b, c [16]byte) (result [16]byte)

//go:noescape
func add_pd(a, b [16]byte) (result [16]byte)

//go:noescape
func mul_pd(a, b [16]byte) (result [16]byte)

//go:noescape
func add_epi32(a, b [16]byte) (result [16]byte)

//go:noescape
func hsum_ps(v [16]byte) (result float32)

//go:noescape
func dot_ps(a, b [16]byte) (result float32)

//go:noescape
func add256_ps(a, b [32]byte) (result [32]byte)

//go:noescape
func mul256_ps(a, b [32]byte) (result [32]byte)

//go:noescape
func fma256_ps(a, b, c [32]byte) (result [32]byte)

//go:noescape
func add256_pd(a, b [32]byte) (result [32]byte)

//go:noescape
func mul256_pd(a, b [32]byte) (result [32]byte)

//go:noescape
func add256_epi32(a, b [32]byte) (result [32]byte)

//go:noescape
func hsum256_ps(v [32]byte) (result float32)

//go:noescape
func dot256_ps(a, b [32]byte) (result float32)
