//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv9-a+sme -O3
// source: tests/src/sve_test.c

TEXT ·add_f32_sve(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD result+16(FP), R2
	MOVD len+24(FP), R3
	WORD $0xf9400068       // ldr	x8, [x3]
	WORD $0xf100051f       // cmp	x8, #1
	BLT  BB0_5
	WORD $0x04bf502a       // rdvl	x10, #1
	WORD $0xeb0a011f       // cmp	x8, x10
	BHS  BB0_6
	WORD $0xd2800009       // mov	x9, #0                          ; =0x0

BB0_3:
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0xd37ef52b // lsl	x11, x9, #2
	WORD $0x8b0b0049 // add	x9, x2, x11
	WORD $0x8b0b002a // add	x10, x1, x11
	WORD $0x8b0b000b // add	x11, x0, x11

BB0_4:
	WORD $0xbc404560 // ldr	s0, [x11], #4
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_4
	WORD $0xd503467f // smstop	sm

BB0_5:
	RET

BB0_6:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x04bf508b // rdvl	x11, #4
	WORD $0xcb00004c // sub	x12, x2, x0
	WORD $0xeb0b019f // cmp	x12, x11
	BLO  BB0_3
	WORD $0xcb01004c // sub	x12, x2, x1
	WORD $0xeb0b019f // cmp	x12, x11
	BLO  BB0_3
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0x04bf57e9 // rdvl	x9, #-1
	WORD $0x8a090109 // and	x9, x8, x9
	WORD $0x2518e3e0 // ptrue	p0.b
	WORD $0xaa0903ec // mov	x12, x9

BB0_9:
	WORD $0x8b0b000d // add	x13, x0, x11
	WORD $0xd503477f // smstart	sm
	WORD $0xa40b4000 // ld1b	{ z0.b }, p0/z, [x0, x11]
	WORD $0x858045a1 // ldr	z1, [x13, #1, mul vl]
	WORD $0x858049a2 // ldr	z2, [x13, #2, mul vl]
	WORD $0x85804da3 // ldr	z3, [x13, #3, mul vl]
	WORD $0x8b0b002d // add	x13, x1, x11
	WORD $0xa40b4024 // ld1b	{ z4.b }, p0/z, [x1, x11]
	WORD $0x858045a5 // ldr	z5, [x13, #1, mul vl]
	WORD $0x858049a6 // ldr	z6, [x13, #2, mul vl]
	WORD $0x85804da7 // ldr	z7, [x13, #3, mul vl]
	WORD $0x65840000 // fadd	z0.s, z0.s, z4.s
	WORD $0x65850021 // fadd	z1.s, z1.s, z5.s
	WORD $0x65860042 // fadd	z2.s, z2.s, z6.s
	WORD $0x65870063 // fadd	z3.s, z3.s, z7.s
	WORD $0x8b0b004d // add	x13, x2, x11
	WORD $0xe40b4040 // st1b	{ z0.b }, p0, [x2, x11]
	WORD $0xe58045a1 // str	z1, [x13, #1, mul vl]
	WORD $0xe58049a2 // str	z2, [x13, #2, mul vl]
	WORD $0xe5804da3 // str	z3, [x13, #3, mul vl]
	WORD $0x0433e3eb // incb	x11, all, mul #4
	WORD $0xeb0a018c // subs	x12, x12, x10
	BNE  BB0_9
	WORD $0xeb09011f // cmp	x8, x9
	BNE  BB0_3
	B    BB0_5

TEXT ·mul_f32_sve(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD result+16(FP), R2
	MOVD len+24(FP), R3
	WORD $0xf9400068       // ldr	x8, [x3]
	WORD $0xf100051f       // cmp	x8, #1
	BLT  BB1_5
	WORD $0x04bf502a       // rdvl	x10, #1
	WORD $0xeb0a011f       // cmp	x8, x10
	BHS  BB1_6
	WORD $0xd2800009       // mov	x9, #0                          ; =0x0

BB1_3:
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0xd37ef52b // lsl	x11, x9, #2
	WORD $0x8b0b0049 // add	x9, x2, x11
	WORD $0x8b0b002a // add	x10, x1, x11
	WORD $0x8b0b000b // add	x11, x0, x11

BB1_4:
	WORD $0xbc404560 // ldr	s0, [x11], #4
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0x1e210800 // fmul	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB1_4
	WORD $0xd503467f // smstop	sm

BB1_5:
	RET

BB1_6:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x04bf508b // rdvl	x11, #4
	WORD $0xcb00004c // sub	x12, x2, x0
	WORD $0xeb0b019f // cmp	x12, x11
	BLO  BB1_3
	WORD $0xcb01004c // sub	x12, x2, x1
	WORD $0xeb0b019f // cmp	x12, x11
	BLO  BB1_3
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0x04bf57e9 // rdvl	x9, #-1
	WORD $0x8a090109 // and	x9, x8, x9
	WORD $0x2518e3e0 // ptrue	p0.b
	WORD $0xaa0903ec // mov	x12, x9

BB1_9:
	WORD $0x8b0b000d // add	x13, x0, x11
	WORD $0xd503477f // smstart	sm
	WORD $0xa40b4000 // ld1b	{ z0.b }, p0/z, [x0, x11]
	WORD $0x858045a1 // ldr	z1, [x13, #1, mul vl]
	WORD $0x858049a2 // ldr	z2, [x13, #2, mul vl]
	WORD $0x85804da3 // ldr	z3, [x13, #3, mul vl]
	WORD $0x8b0b002d // add	x13, x1, x11
	WORD $0xa40b4024 // ld1b	{ z4.b }, p0/z, [x1, x11]
	WORD $0x858045a5 // ldr	z5, [x13, #1, mul vl]
	WORD $0x858049a6 // ldr	z6, [x13, #2, mul vl]
	WORD $0x85804da7 // ldr	z7, [x13, #3, mul vl]
	WORD $0x65840800 // fmul	z0.s, z0.s, z4.s
	WORD $0x65850821 // fmul	z1.s, z1.s, z5.s
	WORD $0x65860842 // fmul	z2.s, z2.s, z6.s
	WORD $0x65870863 // fmul	z3.s, z3.s, z7.s
	WORD $0x8b0b004d // add	x13, x2, x11
	WORD $0xe40b4040 // st1b	{ z0.b }, p0, [x2, x11]
	WORD $0xe58045a1 // str	z1, [x13, #1, mul vl]
	WORD $0xe58049a2 // str	z2, [x13, #2, mul vl]
	WORD $0xe5804da3 // str	z3, [x13, #3, mul vl]
	WORD $0x0433e3eb // incb	x11, all, mul #4
	WORD $0xeb0a018c // subs	x12, x12, x10
	BNE  BB1_9
	WORD $0xeb09011f // cmp	x8, x9
	BNE  BB1_3
	B    BB1_5

TEXT ·fma_f32_sve(SB), $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD result+24(FP), R3
	MOVD len+32(FP), R4
	WORD $0xf9400088       // ldr	x8, [x4]
	WORD $0xf100051f       // cmp	x8, #1
	BLT  BB2_5
	WORD $0xf1000d1f       // cmp	x8, #3
	BHI  BB2_6
	WORD $0xd2800009       // mov	x9, #0                          ; =0x0

BB2_3:
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0xd37ef52c // lsl	x12, x9, #2
	WORD $0x8b0c0069 // add	x9, x3, x12
	WORD $0x8b0c004a // add	x10, x2, x12
	WORD $0x8b0c002b // add	x11, x1, x12
	WORD $0x8b0c000c // add	x12, x0, x12

BB2_4:
	WORD $0xbc404580 // ldr	s0, [x12], #4
	WORD $0xbc404561 // ldr	s1, [x11], #4
	WORD $0xbc404542 // ldr	s2, [x10], #4
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbc004520 // str	s0, [x9], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB2_4

BB2_5:
	RET

BB2_6:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0xcb00006a // sub	x10, x3, x0
	WORD $0xf101015f // cmp	x10, #64
	BLO  BB2_3
	WORD $0xcb01006a // sub	x10, x3, x1
	WORD $0xf101015f // cmp	x10, #64
	BLO  BB2_3
	WORD $0xcb02006a // sub	x10, x3, x2
	WORD $0xf101015f // cmp	x10, #64
	BLO  BB2_3
	WORD $0xf100411f // cmp	x8, #16
	BHS  BB2_11
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	B    BB2_15

BB2_11:
	WORD $0x927ce909 // and	x9, x8, #0x7ffffffffffffff0
	WORD $0x9100800a // add	x10, x0, #32
	WORD $0x9100802b // add	x11, x1, #32
	WORD $0x9100806c // add	x12, x3, #32
	WORD $0x9100804d // add	x13, x2, #32
	WORD $0xaa0903ee // mov	x14, x9

BB2_12:
	WORD $0xad7f0540 // ldp	q0, q1, [x10, #-32]
	WORD $0xacc20d42 // ldp	q2, q3, [x10], #64
	WORD $0xad7f1564 // ldp	q4, q5, [x11, #-32]
	WORD $0xacc21d66 // ldp	q6, q7, [x11], #64
	WORD $0xad7f45b0 // ldp	q16, q17, [x13, #-32]
	WORD $0xacc24db2 // ldp	q18, q19, [x13], #64
	WORD $0x4e20cc90 // fmla.4s	v16, v4, v0
	WORD $0x4e21ccb1 // fmla.4s	v17, v5, v1
	WORD $0x4e22ccd2 // fmla.4s	v18, v6, v2
	WORD $0x4e23ccf3 // fmla.4s	v19, v7, v3
	WORD $0xad3f4590 // stp	q16, q17, [x12, #-32]
	WORD $0xac824d92 // stp	q18, q19, [x12], #64
	WORD $0xf10041ce // subs	x14, x14, #16
	BNE  BB2_12
	WORD $0xeb09011f // cmp	x8, x9
	BEQ  BB2_5
	WORD $0xf27e051f // tst	x8, #0xc
	BEQ  BB2_3

BB2_15:
	WORD $0xaa0903eb // mov	x11, x9
	WORD $0x927ef109 // and	x9, x8, #0x7ffffffffffffffc
	WORD $0xcb09016a // sub	x10, x11, x9
	WORD $0xd37ef56e // lsl	x14, x11, #2
	WORD $0x8b0e006b // add	x11, x3, x14
	WORD $0x8b0e004c // add	x12, x2, x14
	WORD $0x8b0e002d // add	x13, x1, x14
	WORD $0x8b0e000e // add	x14, x0, x14

BB2_16:
	WORD $0x3cc105c0 // ldr	q0, [x14], #16
	WORD $0x3cc105a1 // ldr	q1, [x13], #16
	WORD $0x3cc10582 // ldr	q2, [x12], #16
	WORD $0x4e20cc22 // fmla.4s	v2, v1, v0
	WORD $0x3c810562 // str	q2, [x11], #16
	WORD $0xb100114a // adds	x10, x10, #4
	BNE  BB2_16
	WORD $0xeb09011f // cmp	x8, x9
	BNE  BB2_3
	B    BB2_5

TEXT ·dot_f32_sve(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD result+16(FP), R2
	MOVD len+24(FP), R3
	WORD $0xf9400068       // ldr	x8, [x3]
	WORD $0xf100051f       // cmp	x8, #1
	BLT  BB3_3
	WORD $0x04bf502a       // rdvl	x10, #1
	WORD $0xeb0a011f       // cmp	x8, x10
	BHS  BB3_4
	WORD $0xd2800009       // mov	x9, #0                          ; =0x0
	WORD $0x1e2703e0       // fmov	s0, wzr
	B    BB3_7

BB3_3:
	WORD $0x1e2703e0 // fmov	s0, wzr
	WORD $0xbd000040 // str	s0, [x2]
	WORD $0xd503467f // smstop	sm
	RET

BB3_4:
	WORD $0x04bf57e9 // rdvl	x9, #-1
	WORD $0x8a090109 // and	x9, x8, x9
	WORD $0x1e2703e0 // fmov	s0, wzr
	WORD $0x2598e3e0 // ptrue	p0.s
	WORD $0xaa0003eb // mov	x11, x0
	WORD $0xaa0103ec // mov	x12, x1
	WORD $0xaa0903ed // mov	x13, x9

BB3_5:
	WORD $0x85804161 // ldr	z1, [x11]
	WORD $0x85804562 // ldr	z2, [x11, #1, mul vl]
	WORD $0x85804963 // ldr	z3, [x11, #2, mul vl]
	WORD $0x85804d64 // ldr	z4, [x11, #3, mul vl]
	WORD $0x85804185 // ldr	z5, [x12]
	WORD $0x85804586 // ldr	z6, [x12, #1, mul vl]
	WORD $0x85804987 // ldr	z7, [x12, #2, mul vl]
	WORD $0x85804d90 // ldr	z16, [x12, #3, mul vl]
	WORD $0xd503477f // smstart	sm
	WORD $0x65850821 // fmul	z1.s, z1.s, z5.s
	WORD $0x65860842 // fmul	z2.s, z2.s, z6.s
	WORD $0x65870863 // fmul	z3.s, z3.s, z7.s
	WORD $0x65900884 // fmul	z4.s, z4.s, z16.s
	WORD $0x65982020 // fadda	s0, p0, s0, z1.s
	WORD $0x65982040 // fadda	s0, p0, s0, z2.s
	WORD $0x65982060 // fadda	s0, p0, s0, z3.s
	WORD $0x65982080 // fadda	s0, p0, s0, z4.s
	WORD $0x0433e3ec // incb	x12, all, mul #4
	WORD $0x0433e3eb // incb	x11, all, mul #4
	WORD $0xeb0a01ad // subs	x13, x13, x10
	BNE  BB3_5
	WORD $0xeb09011f // cmp	x8, x9
	BEQ  BB3_9

BB3_7:
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0xd37ef52a // lsl	x10, x9, #2
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10

BB3_8:
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0xbc404522 // ldr	s2, [x9], #4
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB3_8

BB3_9:
	WORD $0xbd000040 // str	s0, [x2]
	WORD $0xd503467f // smstop	sm
	RET
