//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv9-a+sme -O3
// source: tests/src/sve_test.c

package tests

import "unsafe"

//go:noescape
func add_f32_sve(a, b, result, len unsafe.Pointer)

//go:noescape
func mul_f32_sve(a, b, result, len unsafe.Pointer)

//go:noescape
func fma_f32_sve(a, b, c, result, len unsafe.Pointer)

//go:noescape
func dot_f32_sve(a, b, result, len unsafe.Pointer)
